/**
 * @NApiVersion 2.1
 * @NScriptType Suitelet
 */
// This sample shows how to render search results into a PDF file.
define(["N/render", "N/search", "N/record", "N/log", "N/file", "N/http", 'N/config', 'N/format', 'N/email', 'N/runtime'],
    function(render, search, record, log, file, http, config, format, email, runtime) {
        function removeDecimalFormat(number) {
            return number.toString().substring(0, number.toString().length - 3);
        }
        function pembulatan(angka) {
            if (angka >= 0) {
                var bulat = Math.floor(angka);
                var desimal = angka - bulat;
                
                if (desimal >= 0.5) {
                    return Math.ceil(angka);
                } else {
                return Math.floor(angka);
                }
            } else {
                return Math.ceil(angka);
            }
        }

        function onRequest(context) {
            var recid = context.request.parameters.id;
            // load PO
            var poSavedLoad = search.load({
                id: "customsearch_pr_body_for_print_out",
            });
            if(recid){
                poSavedLoad.filters.push(search.createFilter({name: "internalid", operator: search.Operator.IS, values: recid}));
            }
            var poSavedLoadSet = poSavedLoad.run();
            var result = poSavedLoadSet.getRange(0, 1);
            var poRecord = result[0];

            var companyInfo = config.load({
                type: config.Type.COMPANY_INFORMATION
            });
            var compAddress = companyInfo.getValue('mainaddress_text');
            var legalName = companyInfo.getValue("legalname");

            var logo = companyInfo.getValue('formlogo');
            var filelogo;
            var urlLogo = '';
            if (logo) {
                filelogo = file.load({
                    id: logo
                });
                //get url
                urlLogo = filelogo.url.replace(/&/g, "&amp;");
            }

            var vendor_id = poRecord.getValue({
                name: "internalid",
                join: "vendor",
            });
            if(vendor_id){
                var vendorRecord = record.load({
                    type: record.Type.VENDOR,
                    id: vendor_id,
                    isDynamic: false,
                });
                var venName
                var vendLeadTime
                var isperson = vendorRecord.getValue('isperson');
                if(isperson == 'T'){
                    var firstname = vendorRecord.getValue('firstname') || ''
                    var middleName = vendorRecord.getValue('middlename') || '';
                    var lastname = vendorRecord.getValue('lastname')|| ''
                    venName = firstname + ' '+ middleName+ ' ' + lastname;
                }else{
                    var isChecklist = vendorRecord.getValue('isautogeneratedrepresentingentity');

                    if(isChecklist === true){
                        venName = vendorRecord.getValue('comments');
                    }else{
                        venName = vendorRecord.getValue('companyname');
                    }
                    
                }
                var venAddres = vendorRecord.getValue('billaddr1');
                if(venAddres === ''){
                    venAddres = vendorRecord.getValue('defaultaddress');
                }
                if(venAddres){
                    if(venAddres.includes('&')){
                        venAddres = venAddres.replace(/&/g, ' dan ')
                    }
                }
                vendLeadTime =  vendorRecord.getValue('custentity1');

            }
            // PO data
            var tandId = poRecord.getValue({
                name: "tranid"
            });
            var POdate = poRecord.getValue({
                name: "trandate"
            });
            var busdev = poRecord.getValue({
                name: "custbody_abj_sales_rep_fulfillment"
            });
            var noForm = poRecord.getValue({
                name: "custbody_abj_no_form"
            }) || ""
            var busdevName = ""
            if(busdev){
                var empRec = record.load({
                    type: "employee",
                    id: busdev,
                    isDynamic: false,
                });
                var altName = empRec.getValue('altname')
                busdevName = altName
            }
            // if(POdate){
            //     POdate = format.format({
            //         value: POdate,
            //         type: format.Type.DATE
            //     });
            // }

            var response = context.response;
            var xml = "";
            var header = "";
            var body = "";
            var headerHeight = '0%';
            var style = "";
            var footer = "";
            var pdfFile = null;

            
            style += "<style type='text/css'>";
            style += ".tg {border-collapse:collapse; border-spacing: 0; width: 100%;}";
            style += ".tg .tg-headerlogo{align:center; border-right: none;border-left: none;border-top: none;border-bottom: none;}";
            style += ".tg .tg-img-logo{width:210px; height:60px; object-vit:cover;}";
            style += ".tg .tg-headerrow{align: right;font-size:9px;}";
            style += ".tg .tg-headerrow_legalName{align: right;font-size:10px;word-break:break-all; font-weight: bold;}";
            style += ".tg .tg-headerrow_Total{align: right;font-size:10px;word-break:break-all; font-weight: bold;}";
            style += ".tg .tg-headerrow_left{align: left;font-size:9px;}";
            style += ".tg .tg-head_body{align: center;font-size:6px;font-weight: bold; border: 1px solid black;}";
            style += ".tg .tg-b_body{align: left;font-size:6px; border: 1px solid black;}";
            style += ".tg .tg-f_body{align: right;font-size:6px;border-bottom: solid black 2px;}";
            style += ".tg .tg-foot{font-size:9px; color: #808080; position: absolute; bottom: 0;}";
            style += "</style>";


            header += "<table class='tg' width=\"100%\"  style=\"table-layout:fixed;\">";
            header += "<tbody>";
            header += "</tbody>";
            header += "</table>";

            body += "<table class='tg' width=\"100%\"  style=\"table-layout:fixed;\">";
            body += "<tbody>";
            body += "<tr>";
            if (urlLogo) {
                body += "<td class='tg-headerlogo' style='width:100%;vertical-align:center; align:center;'><div style='display: flex; height:60px; width:210px;'><img class='tg-img-logo' src= '" + urlLogo + "' ></img></div></td>";
            }
            body += "</tr>";
            body += "<tr>";
            body += "<td style='align:right; font-size:9px; font-weight: bold;'>No. Form : "+noForm+" </td>"
            body += "</tr>";
            body += "<tr>";
            body += "<td style='align:center; font-size:9px;'>"+compAddress+" </td>"
            body += "</tr>";
            body += "<tr>";
            body += "<td style='align:center; border-bottom:1px solid black; border-top:1px solid black'></td>"
            body += "</tr>";
            body += "<tr>";
            body += "<td style='align:center; font-size:9px; font-weight: bold;'>PURCHASE REQUEST ("+venName+") </td>"
            body += "</tr>";
            body += "</tbody>";
            body += "</table>";

            body += "<table class='tg' width=\"100%\"  style=\"table-layout:fixed; font-size:7px;\">";
            body += "<tbody>";
            body += "<tr>";
            body += "<td style='width:17%'></td>"
            body += "<td style='width:83%'></td>"
            body += "</tr>";

            body += "<tr>";
            body += "<td style='font-weight: bold;'>PRINCIPALS</td>"
            body += "<td style=''>: "+venName+"</td>"
            body += "</tr>";

            body += "<tr>";
            body += "<td style='font-weight: bold;'>TANGGAL</td>"
            body += "<td style=''>: "+POdate+"</td>"
            body += "</tr>";

            body += "<tr>";
            body += "<td style='font-weight: bold;'>NO. PURCHASE REQUEST</td>"
            body += "<td style=''>: "+tandId+"</td>"
            body += "</tr>";

            body += "<tr>";
            body += "<td style='font-weight: bold;'>LEAD TIME</td>"
            body += "<td style=''>: "+vendLeadTime+"</td>"
            body += "</tr>";

            body += "</tbody>";
            body += "</table>";

            body += "<table class='tg' width=\"100%\" style=\"table-layout:fixed;\">";
            body += "<tbody>";
            
            body += "<tr>";
            body += "<td style='width:3%'></td>"
            body += "<td style='width:5%'></td>"
            body += "<td style='width:10%'></td>"
            body += "<td style='width:8%'></td>"
            body += "<td style='width:4%'></td>"
            body += "<td style='width:4%'></td>"
            body += "<td style='width:10%'></td>"
            body += "<td style='width:4%'></td>"
            body += "<td style='width:9%'></td>"
            body += "<td style='width:7%'></td>"
            body += "<td style='width:5%'></td>"
            body += "<td style='width:5%'></td>"
            body += "<td style='width:5%'></td>"
            body += "<td style='width:5%'></td>"
            body += "<td style='width:6%'></td>"
            body += "<td style='width:10%'></td>"
            body += "</tr>";

            body += "<tr>";
            body += "<td class='tg-head_body' style='background-color:#72C9FA; vertical-align:center; border-right:none; align:center' rowspan='2'> NO </td>"
            body += "<td class='tg-head_body' style='background-color:#72C9FA; vertical-align:center; border-right:none; align:center' rowspan='2'> INVENTORY ID </td>"
            body += "<td class='tg-head_body' style='background-color:#72C9FA; vertical-align:center; border-right:none; align:center' rowspan='2'> INVENTORY NAME </td>"
            body += "<td class='tg-head_body' style='background-color:#72C9FA; vertical-align:center; border-right:none; align:center' rowspan='2'> CURRENT STOCK </td>"
            body += "<td class='tg-head_body' style='background-color:#72C9FA; vertical-align:center; border-right:none; align:center' rowspan='2'> INCOMING STOCK </td>"
            body += "<td class='tg-head_body' style='background-color:#72C9FA; vertical-align:center; border-right:none; align:center' rowspan='2'> SALES </td>"
            body += "<td class='tg-head_body' style='background-color:#72C9FA; vertical-align:center; border-right:none; align:center' rowspan='2'> CUSTOMER </td>"
            body += "<td class='tg-head_body' style='background-color:#72C9FA; vertical-align:center; border-right:none; align:center' rowspan='2'> OS.PO </td>"
            body += "<td class='tg-head_body' style='background-color:#72C9FA; vertical-align:center; border-right:none; align:center' rowspan='2'> NO. PO </td>"
            body += "<td class='tg-head_body' style='background-color:#72C9FA; vertical-align:center; border-right:none; align:center' rowspan='2'> TANGGAL KIRIM </td>"
            body += "<td class='tg-head_body' style='background-color:#72C9FA; align:center; border-right:none;' colspan='2'> FORECAST  BUFFER STOCK </td>"
            body += "<td class='tg-head_body' style='background-color:#72C9FA; align:center; border-right:none;' colspan='2'> RATA RATA PENGIRIMAN </td>"
            body += "<td class='tg-head_body' style='background-color:#72C9FA; vertical-align:center; border-right:none; align:center' rowspan='2'> TOTAL ORDER </td>"
            body += "<td class='tg-head_body' style='background-color:#72C9FA; vertical-align:center; align:center' rowspan='2'> NOTE </td>"
            body += "</tr>";

            body += "<tr>";
            body += "<td class='tg-head_body' style='background-color:#72C9FA; border-right:none;'> BUSDEV </td>"
            body += "<td class='tg-head_body' style='background-color:#72C9FA; border-right:none;'> RUMUS <br/> PEHITUNGAN </td>"
            body += "<td class='tg-head_body' style='background-color:#72C9FA; border-right:none;'> BUSDEV </td>"
            body += "<td class='tg-head_body' style='background-color:#72C9FA; border-right:none;'> ACCOUNTING </td>"
            body += "</tr>";
            body += getPOItem(context, recid);
            body += "</tbody>";
            body += "</table>";

            body += "<table class='tg' width=\"100%\" style=\"table-layout:fixed;font-size:7px;\">";
            body += "<tbody>";
            body += "<tr>"
            body += "<td style='width:5%'></td>"
            body += "<td style='width:1%'></td>"
            body += "<td style='width:17%'></td>"
            body += "<td style='width:1%'></td>"
            body += "<td style='width:5%'></td>"
            body += "<td style='width:1%'></td>"
            body += "<td style='width:17%'></td>"
            body += "<td style='width:1%'></td>"
            body += "<td style='width:5%'></td>"
            body += "<td style='width:1%'></td>"
            body += "<td style='width:17%'></td>"
            body += "<td style='width:1%'></td>"
            body += "<td style='width:5%'></td>"
            body += "<td style='width:1%'></td>"
            body += "<td style='width:16%'></td>"
            body += "<td style='width:1%'></td>"
            body += "<td style='width:5%'></td>"
            body += "</tr>";

            body += "<tr>"
            body += "<td style=''></td>"
            body += "<td style=''></td>"
            body += "<td style='align:center;'>DIBUAT OLEH,</td>"
            body += "<td style=''></td>"
            body += "<td style=''></td>"
            body += "<td style=''></td>"
            body += "<td style='align:center;'>DIPERIKSA OLEH,</td>"
            body += "<td style=''></td>"
            body += "<td style=''></td>"
            body += "<td style=''></td>"
            body += "<td style='align:center;'>DISETUJUI OLEH,</td>"
            body += "<td style=''></td>"
            body += "<td style=''></td>"
            body += "<td style=''></td>"
            body += "<td style='align:center;'>DIKETAHUI OLEH,</td>"
            body += "<td style=''></td>"
            body += "<td style=''></td>"
            body += "</tr>";
            body += "<tr>"
            body += "<td style='height:40px' colspan='20'></td>"
            body += "</tr>";

            body += "<tr>"
            body += "<td style=''></td>"
            body += "<td style=''>(</td>"
            body += "<td style='align:center;'>"+busdevName+"</td>"
            body += "<td style=''>}</td>"
            body += "<td style=''></td>"
            body += "<td style=''>(</td>"
            body += "<td style='align:center;'>ACCOUNTING</td>"
            body += "<td style=''>)</td>"
            body += "<td style=''></td>"
            body += "<td style=''>(</td>"
            body += "<td style='align:center;'>OPERATIONAL DIRECTOR</td>"
            body += "<td style=''>)</td>"
            body += "<td style=''></td>"
            body += "<td style=''>(</td>"
            body += "<td style='align:center;'>PRESIDENT DIRECTOR</td>"
            body += "<td style=''>)</td>"
            body += "<td style=''></td>"
            body += "</tr>";

            body += "</tbody>";
            body += "</table>";

            footer += "<table class='tg' style='table-layout: fixed;'>";
            footer += "<tbody>";
            footer += "<tr class='tg-foot'>";
            footer += "<td style='align:right'></td>"
            footer += "</tr>";
            footer += "</tbody>";
            footer += "</table>";

            var xml = '<?xml version="1.0"?>\n<!DOCTYPE pdf PUBLIC "-//big.faceless.org//report" "report-1.1.dtd">';
            xml += "<pdf>";
            xml += "<head>";
            xml += style;
            xml += "<macrolist>";
            xml += "<macro id=\"nlheader\">";
            xml += header;
            xml += "</macro>";
            xml += "<macro id=\"nlfooter\">";
            xml += footer;
            xml += "</macro>";
            xml += "</macrolist>";
            xml += "</head>"
            xml += "<body font-size='8' style='font-family: Tahoma,sans-serif;height: 21cm; width: 29.7cm;' header='nlheader' header-height='" + headerHeight + "' footer='nlfooter' footer-height='3%'>";
            xml += body;
            xml += "\n</body>\n</pdf>";

            xml = xml.replace(/ & /g, ' &amp; ');
            response.renderPdf({
                xmlString: xml
            });

        }
        function generateTableHTML(itemId, dataItem, nomor) {
            // Mengambil item pertama dari grup
            var firstItem = dataItem.items[0];
            var fieldLookUpSection = search.lookupFields({
                type: "item",
                id: itemId,
                columns: ["itemid"],
            });
            var itemName = fieldLookUpSection.itemid;
            var itemParts = itemName.split(' ', 2);
            var itemCode = itemParts[0];
            var itemDescription = itemName.substring(itemCode.length + 1);
        
            let html = `<tr>
                <td class='tg-b_body' style="border-right: 1px solid black; vertical-align:center; align:center; border-right:none;">${nomor}</td>
                <td class='tg-b_body' style="border-right: 1px solid black; vertical-align:center; align:center; border-right:none;">${itemCode}</td>
                <td class='tg-b_body' style="border-right: 1px solid black; vertical-align:center; align:center; border-right:none;">${itemDescription}</td>
                <td class='tg-b_body' style="border-right: 1px solid black; border-right:none;">${dataItem.totalOnHand}</td>
                <td class='tg-b_body' style="border-right: 1px solid black; border-right:none;">${dataItem.totalInComingStock}</td>
                <td class='tg-b_body' style="border-right: 1px solid black; border-right:none;">${firstItem.salesRepCode}</td>
                <td class='tg-b_body' style="border-right: 1px solid black; border-right:none;">${firstItem.customer}</td>
                <td class='tg-b_body' style="border-right: 1px solid black; border-right:none;">${dataItem.totalOsPO}</td>
                <td class='tg-b_body' style="border-right: 1px solid black; border-right:none;">${firstItem.noSO}</td>
                <td class='tg-b_body' style="border-right: 1px solid black; border-right:none;">${firstItem.tglKirim}</td>
                <td class='tg-b_body' style="border-right: 1px solid black; border-right:none;">${dataItem.totalForecase}</td>
                <td class='tg-b_body' style="border-right: 1px solid black; border-right:none;">${firstItem.leadTimeKirim}</td>
                <td class='tg-b_body' style="border-right: 1px solid black; border-right:none;">${firstItem.avgpengBusdev}</td>
                <td class='tg-b_body' style="border-right: 1px solid black; border-right:none;">${firstItem.avgpengAcc}</td>
                <td class='tg-b_body' style="border-right: 1px solid black; border-right:none;">${dataItem.totalQty}</td>
                <td class='tg-b_body' style="border-right: 1px solid black;">${dataItem.lastNotes}</td>
            </tr>`;
            
            // Baris tambahan untuk subtotal, jika diperlukan
            html += `<tr>
                <td class='tg-b_body' style="border-right: 1px solid black; background-color:yellow; border-right:none;"></td>
                <td class='tg-b_body' style="border-right: 1px solid black; background-color:yellow; border-right:none;"></td>
                <td class='tg-b_body' style="border-right: 1px solid black; background-color:yellow; border-right:none;"></td>
                <td class='tg-b_body' style="border-right: 1px solid black; background-color:yellow; font-weight:bold; border-right:none;">${dataItem.totalOnHand}</td>
                <td class='tg-b_body' style="border-right: 1px solid black; background-color:yellow; font-weight:bold; border-right:none;">${dataItem.totalInComingStock}</td>
                <td class='tg-b_body' style="border-right: 1px solid black; background-color:yellow; border-right:none;"></td>
                <td class='tg-b_body' style="border-right: 1px solid black; background-color:yellow; border-right:none;"></td>
                <td class='tg-b_body' style="border-right: 1px solid black; background-color:yellow; font-weight:bold; border-right:none;">${dataItem.totalOsPO}</td>
                <td class='tg-b_body' style="border-right: 1px solid black; background-color:yellow; border-right:none;"></td>
                <td class='tg-b_body' style="border-right: 1px solid black; background-color:yellow; border-right:none;"></td>
                <td class='tg-b_body' style="border-right: 1px solid black; background-color:yellow; font-weight:bold; border-right:none;">${dataItem.totalForecase}</td>
                <td class='tg-b_body' style="border-right: 1px solid black; background-color:yellow; border-right:none;"></td>
                <td class='tg-b_body' style="border-right: 1px solid black; background-color:yellow; border-right:none;"></td>
                <td class='tg-b_body' style="border-right: 1px solid black; background-color:yellow; border-right:none;"></td>
                <td class='tg-b_body' style="border-right: 1px solid black; background-color:yellow; font-weight:bold; border-right:none;">${dataItem.totalQty}</td>
                <td class='tg-b_body' style="border-right: 1px solid black; background-color:yellow; font-weight:bold;"></td>
            </tr>`;
            
            return html;
        }
        
        var dataItem = []
        function getPOItem(context, recid){
            var itemSearch =  search.load({
                id: "customsearch_pr_line_for_printout",
            });
            if(recid){
                itemSearch.filters.push(search.createFilter({name: "internalid", operator: search.Operator.IS, values: recid}));
            }
            var itemSearchSet = itemSearch.run();
            var itemCount = itemSearchSet.getRange(0, 100);
            if(itemCount.length > 0){
                
                var body = "";
                for(var index = 0; index < itemCount.length; index++){
                    var poRecord = itemCount[index]
                    var itemId = poRecord.getValue({
                        name: "custrecord_iss_pr_item",
                        join: "CUSTRECORD_ISS_PR_PARENT",
                    });
                    var itemText = poRecord.getText({
                        name: "custrecord_iss_pr_item",
                        join: "CUSTRECORD_ISS_PR_PARENT",
                    });
                    var itemParts = itemText.split(' ', 2);
                    var itemCode = itemParts[0]; 
                    var itemDescription = itemText.substring(itemCode.length + 1); 

                    
                    var onHand = parseFloat(poRecord.getValue({
                        name: "custrecord_iss_pr_stock",
                        join: "CUSTRECORD_ISS_PR_PARENT",
                    })) || 0;
                    var inComingStock = parseFloat(poRecord.getValue({
                        name: "custrecord_iss_pr_incoming_stock",
                        join: "CUSTRECORD_ISS_PR_PARENT",
                    })) || 0;
                    var salesRepCode = poRecord.getText({
                        name: "custrecord_prsum_salesrep",
                        join: "CUSTRECORD_ISS_PR_PARENT",
                    });
                    var customer = poRecord.getText({
                        name: "custrecord_prsum_customer",
                        join: "CUSTRECORD_ISS_PR_PARENT",
                    });
                    var customerId = poRecord.getValue({
                        name: "custrecord_prsum_customer",
                        join: "CUSTRECORD_ISS_PR_PARENT",
                    });
                    var osPO = parseFloat(poRecord.getValue({
                        name: "custrecord_iss_os_po",
                        join: "CUSTRECORD_ISS_PR_PARENT",
                    })) || 0;
                    var noSO = poRecord.getText({
                        name: "custrecord_iss_no_po",
                        join: "CUSTRECORD_ISS_PR_PARENT",
                    });
                    var noSOId = poRecord.getValue({
                        name: "custrecord_iss_no_po",
                        join: "CUSTRECORD_ISS_PR_PARENT",
                    });
                    var tglKirim = poRecord.getValue({
                        name: "custrecord_iss_tgl_kirim",
                        join: "CUSTRECORD_ISS_PR_PARENT",
                    });
                    
                    var forecase = parseFloat(poRecord.getValue({
                        name: "custrecord_iss_forecast_buffer",
                        join: "CUSTRECORD_ISS_PR_PARENT",
                    })) || 0;
                    var leadTimeKirim = poRecord.getValue({
                        name: "custrecord_iss_lead_time",
                        join: "CUSTRECORD_ISS_PR_PARENT",
                    });
                    var avgpengBusdev = poRecord.getValue({
                        name: "custrecord_iss_avg_busdev",
                        join: "CUSTRECORD_ISS_PR_PARENT",
                    });
                    var avgpengAcc = poRecord.getValue({
                        name: "custrecord_iss_avg_accounting",
                        join: "CUSTRECORD_ISS_PR_PARENT",
                    });
                    var qty = parseFloat(poRecord.getValue({
                        name: "custrecord_iss_total_order",
                        join: "CUSTRECORD_ISS_PR_PARENT",
                    })) || 0;
                    var notes = poRecord.getValue({
                        name: "custrecord_iss_note",
                        join: "CUSTRECORD_ISS_PR_PARENT",
                    });
                    dataItem.push({
                        itemId : itemId,
                        itemText : itemText,
                        itemDescription : itemDescription,
                        itemCode : itemCode,
                        onHand : onHand,
                        inComingStock : inComingStock,
                        salesRepCode : salesRepCode,
                        customer : customer,
                        osPO : osPO,
                        noSO : noSO,
                        tglKirim : tglKirim,
                        forecase : forecase,
                        leadTimeKirim : leadTimeKirim,
                        avgpengBusdev : avgpengBusdev,
                        avgpengAcc : avgpengAcc,
                        qty : qty,
                        notes : notes,
                        customerId : customerId
                    })
                }
                log.debug('dataItem', dataItem)
                var dataItemLength = dataItem.length
                var groupedItems = {};
                dataItem.forEach((item) => {
                    if (!groupedItems[item.itemId]) {
                        groupedItems[item.itemId] = {};
                    }
                
                    if (!groupedItems[item.itemId][item.customerId]) {
                        groupedItems[item.itemId][item.customerId] = {
                            totalOnHand: 0,
                            totalInComingStock: 0,
                            totalOsPO: 0,
                            totalForecase: 0,
                            totalQty: 0,
                            lastNotes: '',
                            items: []
                        };
                    }
                
                    groupedItems[item.itemId][item.customerId].totalOnHand += item.onHand;
                    groupedItems[item.itemId][item.customerId].totalInComingStock += item.inComingStock;
                    groupedItems[item.itemId][item.customerId].totalOsPO += item.osPO;
                    groupedItems[item.itemId][item.customerId].totalForecase += item.forecase;
                    groupedItems[item.itemId][item.customerId].totalQty += item.qty;
                    groupedItems[item.itemId][item.customerId].lastNotes = item.notes;
                
                    groupedItems[item.itemId][item.customerId].items.push(item);
                });
                
                log.debug('groupedItems', groupedItems);
                
                let tableHTML = "";
                var nomor = 1;
                for (const itemId in groupedItems) {
                    if (groupedItems.hasOwnProperty(itemId)) {
                        for (const customerId in groupedItems[itemId]) {
                            if (groupedItems[itemId].hasOwnProperty(customerId)) {
                                const groupData = groupedItems[itemId][customerId];
                                tableHTML += generateTableHTML(itemId, groupData, nomor, customerId);
                                nomor++;
                            }
                        }
                    }
                }
                body += tableHTML;
                return body;

            }
            
        }
        
    return {
        onRequest: onRequest,
    };
});